#!/usr/bin/env node
import { readFile } from 'node:fs/promises';
import path from 'node:path';

const projectRoot = path.resolve(new URL('.', import.meta.url).pathname, '..');

async function readSiteVersion() {
  try {
    const versionFile = path.join(projectRoot, 'src', 'siteVersion.ts');
    const file = await readFile(versionFile, 'utf8');
    const match = file.match(/SITE_VERSION\s*=\s*'([^']+)'/);
    return match ? match[1] : 'unknown';
  } catch (error) {
    return 'unknown';
  }
}

function logSection(title) {
  console.log(`\n=== ${title} ===`);
}

(async () => {
  const siteVersion = await readSiteVersion();
  console.log('Deployment helper for jump.bg hosting');
  console.log(`Site version: ${siteVersion}`);

  logSection('Static site files');
  console.log('1. Run "npm install" to ensure dependencies are available.');
  console.log('2. Build the production bundle with "npm run build".');
  console.log('3. Upload the contents of the "dist" directory to your jump.bg public_html folder.');
  console.log('   - Include all subdirectories and asset files generated by Vite.');
  console.log('   - Remove old files from the hosting target before uploading to avoid stale assets.');

  logSection('Contact form API (Node.js server)');
  console.log('If you host the email contact API on jump.bg:');
  console.log('1. Upload the "server" directory, along with "package.json" and "package-lock.json".');
  console.log('2. Ensure Node.js 20+ is available and install dependencies with "npm ci --omit=dev".');
  console.log('3. Provide the required environment variables (SMTP credentials) in a ".env" file.');
  console.log('4. Start the server with "node server/index.mjs" behind a process manager (e.g., pm2).');

  logSection('Environment configuration');
  console.log('Do not upload local ".env" files containing secrets to version control.');
  console.log('Create the ".env" file directly on jump.bg with the SMTP settings provided by your mail service.');
})();
